CREATE TABLE customer (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR2(50),
last_name VARCHAR2(50),
email VARCHAR2(100) NOT NULL
CONSTRAINT valid_email_customer
CHECK (REGEXP_LIKE(email,  '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')),
phone VARCHAR2(10),
register_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE book (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title VARCHAR2(100) NOT NULL,
publication_year NUMBER(4) NOT NULL,
cover_type VARCHAR2(20) NOT NULL CHECK (LOWER(cover_type) IN ('hardcover', 'paperback')),
unit_price NUMBER NOT NULL
);

CREATE TABLE author (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR2(50),
last_name VARCHAR2(50),
about VARCHAR2(1000)
);

CREATE TABLE county (
id VARCHAR2(2) PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE city (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR2(50) NOT NULL,
county_id VARCHAR2(2) NOT NULL,
CONSTRAINT fk_city_county FOREIGN KEY (county_id) REFERENCES county(id)
);

CREATE TABLE book_author (
book_id NUMBER NOT NULL,
author_id NUMBER NOT NULL,
CONSTRAINT pk_book_author PRIMARY KEY (book_id, author_id),
CONSTRAINT fk_book_author_book FOREIGN KEY (book_id) REFERENCES book(id),
CONSTRAINT fk_book_author_author FOREIGN KEY (author_id) REFERENCES author(id)
);

CREATE TABLE supplier (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR2(50) NOT NULL,
email VARCHAR2(100) NOT NULL
CONSTRAINT valid_email_supplier
CHECK (REGEXP_LIKE(email,  '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')),
phone VARCHAR2(10) NOT NULL
);

CREATE TABLE purchase_order (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
supplier_id NUMBER NOT NULL,
order_date DATE DEFAULT SYSDATE NOT NULL
CONSTRAINT fk_purchase_order_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE wishlist (
book_id NUMBER NOT NULL,
customer_id NUMBER NOT NULL,
added_date DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT pk_wishlist PRIMARY KEY (book_id, customer_id),
CONSTRAINT fk_wishlist_book FOREIGN KEY (book_id) REFERENCES book(id),
CONSTRAINT fk_wishlist_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE purchase_order_line (
purchase_order_id NUMBER NOT NULL,
book_id NUMBER NOT NULL,
quantity NUMBER NOT NULL,
unit_price NUMBER(10) NOT NULL,
CONSTRAINT pk_purchase_order_line PRIMARY KEY (purchase_order_id, book_id),
CONSTRAINT fk_pol_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
CONSTRAINT fk_pol_book FOREIGN KEY (book_id) REFERENCES book(id)
);

CREATE TABLE VOUCHER (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
value NUMBER NOT NULL,
validity_date DATE NOT NULL
);

CREATE TABLE ADDRESS (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id NUMBER,
address_line_1 VARCHAR2(100) NOT NULL,
address_line_2 VARCHAR2(100),
city_id NUMBER NOT NULL,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
phone VARCHAR2(10) NOT NULL,
CONSTRAINT fk_address_customer FOREIGN KEY (customer_id) REFERENCES customer(id),
CONSTRAINT fk_address_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE sale_order (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_date DATE DEFAULT SYSDATE NOT NULL,
shipping_address_id NUMBER NOT NULL,
billing_address_id NUMBER NOT NULL,
voucher_id NUMBER,
CONSTRAINT fk_sale_order_shipping FOREIGN KEY (shipping_address_id) REFERENCES ADDRESS(id),
CONSTRAINT fk_sale_order_billing FOREIGN KEY (billing_address_id) REFERENCES ADDRESS(id),
CONSTRAINT fk_sale_order_voucher FOREIGN KEY (voucher_id) REFERENCES VOUCHER(id)
);

CREATE TABLE sale_order_line (
sale_order_id NUMBER NOT NULL,
book_id NUMBER NOT NULL,
quantity NUMBER NOT NULL,
unit_price NUMBER NOT NULL,
CONSTRAINT pk_sale_order_line PRIMARY KEY(sale_order_id,book_id),
CONSTRAINT fk_sol_order FOREIGN KEY(sale_order_id) REFERENCES sale_order(id),
CONSTRAINT fk_sol_book FOREIGN KEY(book_id) REFERENCES book(id)
);

